// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RateLimiter is an autogenerated mock type for the rateLimiter type
type RateLimiter struct {
	mock.Mock
}

type RateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *RateLimiter) EXPECT() *RateLimiter_Expecter {
	return &RateLimiter_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function with given fields: ip
func (_m *RateLimiter) IsAllowed(ip string) bool {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RateLimiter_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type RateLimiter_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ip string
func (_e *RateLimiter_Expecter) IsAllowed(ip interface{}) *RateLimiter_IsAllowed_Call {
	return &RateLimiter_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ip)}
}

func (_c *RateLimiter_IsAllowed_Call) Run(run func(ip string)) *RateLimiter_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RateLimiter_IsAllowed_Call) Return(_a0 bool) *RateLimiter_IsAllowed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RateLimiter_IsAllowed_Call) RunAndReturn(run func(string) bool) *RateLimiter_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// NewRateLimiter creates a new instance of RateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimiter {
	mock := &RateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
